// svelte/frontend/src/App.svelte
<script>
  var idea = ''
  var ideas = []
</script>

<main>
  <h1>My Svelte App</h1>

  <input type='text' bind:value={ idea } />
  <button on:click={ () => ideas = [...ideas, idea] }>Add</button>

  <ul>
    { #each ideas as idea }
      <li>{ idea } <button on:click={ () => ideas = ideas.filter((e, i) => ideas.indexOf(idea) != i) }>Delete</button></li>
    { /each }
  </ul>

  <p>{ ideas.length } awesome ideas.</p>

</main>

<style>

</style>

// vue/frontend/src/App.vue
<script setup>
import { ref } from 'vue'

const idea = ref('')
const ideas = ref([])

const deleteIdea = index => {
  ideas.value.splice(index, 1)
}
</script>

<template>
  <h1>My Vue App</h1>

  <input type='text' v-model='idea' />
  <button @click='ideas.push(idea)'>Add</button>
  <ul>
    <li v-for='idea in ideas' :key='idea'>
      {{ idea }}
      <button @click='deleteIdea(index)'>Delete</button>
    </li>
  </ul>

  <p>{{ ideas.length }} awesome ideas.</p>

</template>
