// vue/frontend/src/App.vue
<script setup>
import { ref } from 'vue'

const idea = ref('')
const ideas = ref([])

const deleteIdea = index => {
  ideas.value.splice(index, 1)
}
</script>

<template>
  <h1>My Vue App</h1>

  <input type='text' v-model='idea' />
  <button @click='ideas.push(idea)'>Add</button>
  <ul>
    <li v-for='idea in ideas' :key='idea'>
      {{ idea }}
      <button @click='deleteIdea(index)'>Delete</button>
    </li>
  </ul>

  <p>{{ ideas.length }} awesome ideas.</p>

</template>

// react/frontend/src/App.js
import { useState } from 'react';
import './App.css';

function App() {
  const [idea, setIdea] = useState('');
  const [ideas, setIdeas] = useState([]);

  const addIdea = idea => {
    setIdeas([...ideas, idea]);
  };

  const deleteIdea = index => {
    const newIdeas = [...ideas];
    newIdeas.splice(index, 1);
    setIdeas(newIdeas);
  };

  return (
    <div className='App'>
      <h1>My React App</h1>

      <input type='text' placeholder='Enter an idea' onChange={ e => setIdea(e.target.value) } />
      <button onClick={ () => addIdea(idea) }>Add Idea</button>
      <ul>
      { ideas.map((idea, index) => (
        <li>
          { idea }
          <button onClick={ () => deleteIdea(index) }>Delete</button>
        </li>
      )) }
      </ul>

      <p>{ ideas.length } awesome ideas.</p>
      
    </div>
  );
}

export default App;
