// angular/frontend/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'frontend';
  ideas : string[] = [];
  addIdea(idea : string) {
    this.ideas.push(idea);
  }

  removeIdea(idea : string) {
    let index = this.ideas.indexOf(idea);
    this.ideas.splice(index, 1);
  }
}
<h1>My Angular App</h1>

<input #idea type='text' placeholder='Enter an idea'>
<button (click)='addIdea(idea.value)'>Add Idea</button>

<ul>
  <li *ngFor='let idea of ideas'>{{ idea }}<button (click)='removeIdea(idea)'>Delete</button></li>
</ul>

<p>{{ ideas.length }} awesome ideas.</p>

// react/frontend/src/App.js
import { useState } from 'react';
import './App.css';

function App() {
  const [idea, setIdea] = useState('');
  const [ideas, setIdeas] = useState([]);

  const addIdea = idea => {
    setIdeas([...ideas, idea]);
  };

  const deleteIdea = index => {
    const newIdeas = [...ideas];
    newIdeas.splice(index, 1);
    setIdeas(newIdeas);
  };

  return (
    <div className='App'>
      <h1>My React App</h1>

      <input type='text' placeholder='Enter an idea' onChange={ e => setIdea(e.target.value) } />
      <button onClick={ () => addIdea(idea) }>Add Idea</button>
      <ul>
      { ideas.map((idea, index) => (
        <li>
          { idea }
          <button onClick={ () => deleteIdea(index) }>Delete</button>
        </li>
      )) }
      </ul>

      <p>{ ideas.length } awesome ideas.</p>
      
    </div>
  );
}

export default App;
